name: Deployment on Developement
on:
  push:
    branches: [ "develope" ]
  workflow_dispatch:

jobs:
  deployment_of_stormannsgal_to_develope:
    name: Deploy Build
    env:
      VUE_APP_API_BASE_URL: 'https://dev.stormannsgal.de'
    runs-on: ubuntu-20.04
    steps:
      - name: Get latest code
        uses: actions/checkout@v4.1.1

      - name: Use latest Node.js
        uses: actions/setup-node@v4

      - name: npm install
        run: npm install

      - name: npm run build
        run: npm run build

      - name: move files
        run: mv -r ./dist/* ./public/

      - name: rsync deployments
        uses: burnett01/rsync-deployments@7.0.1
        with:
          switches: -avz --no-o --no-g --no-perms --no-t --omit-dir-times --delete --exclude-from='.rsync-exclude'
          path: /
          remote_path: ${{ secrets.DEPLOY_PATH_CLIENT_VUEJS_DEV }}
          remote_host: ${{ secrets.DEPLOY_HOST }}
          remote_port: ${{ secrets.DEPLOY_PORT }}
          remote_user: ${{ secrets.DEPLOY_USER }}
          remote_key: ${{ secrets.DEPLOY_KEY }}
          remote_key_pass: ${{ secrets.DEPLOY_KEY_PASS }}

      - name: Deploay Info Success
        uses: rjstone/discord-webhook-notify@v1.0.4
        with:
          severity: info
          details: Successful deployment on build https://dev.stormannsgal.de
          webhookUrl: ${{ secrets.WEBHOOK_DISCORD_URL }}
        if: success()

      - name: Deplay Info Failure
        uses: rjstone/discord-webhook-notify@v1.0.4
        with:
          severity: error
          details: Failure deployment on develope.
          webhookUrl: ${{ secrets.WEBHOOK_DISCORD_URL }}
        if: failure()
